# 1. DataLoader
dataloader: dataloader_mnist
batch_size: 64
num_workers: 8
train_dataset_config:
test_dataset_config:



# 2. Model
model: mnist_NN

# 2. Optimizer
optimizer: adam
optimizer_config:
  lr: 0.001
  weight_decay: 0

# 2. LossFunction
loss: ce_loss

# 2. Scheduler
scheduler: steplr
scheduler_config:
  step_size: 30
  gamma: 0.95


# trainer
default_root_dir: ./results/mnist
profiler: advanced
max_epoch: 200
devices: [1]
accelerator: gpu
num_sanity_val_steps: -1


# save, load
resume_checkpoint: /home/nas3/user/jangyeon/PytorchLightning_framework/results/mnist/lightning_logs/version_1/checkpoints/epoch=03-val_loss=0.3179-val_acc=89.1800.ckpt

# random seed
random_seed: 2301235